---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: test-kopy-ns-src
spec: {}
status: {}
---
apiVersion: v1
data:
  key1: c3VwZXJzZWNyZXQ=
kind: Secret
metadata:
  creationTimestamp: null
  name: fake-secret
  namespace: test-kopy-ns-src
  annotations:
    flynshue.io/sync: "app=foobar"
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: test-ns-kopy-target
  labels:
    app: foobar
spec: {}
status: {}
