name: ci

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: extract versions
        id: versions
        run: |
          VERSION=$(<VERSION)

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "dirty-version=${VERSION}-$(git log --format=%h -1)" >> $GITHUB_OUTPUT
          echo "git-tag=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Check if Tag Exists
        id: check_tag
        run: |
          git ls-remote --exit-code --tags origin '${{ steps.versions.outputs.version }}' && found=true
          if [[ "${found}" == "true" ]]; then
            echo "::error::The ${{ steps.versions.outputs.version }} tag already exists. Please update the version"
            exit 1
          fi

      - name: container registry
        run: |
          echo "${{ env.REGISTRY }}"/${{ env.IMAGE_NAME }}

