name: ci

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: extract versions
        id: versions
        run: |
          VERSION=$(<VERSION)

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "dirty-version=${VERSION}-$(git log --format=%h -1)" >> $GITHUB_OUTPUT
          echo "git-tag=v${VERSION}" >> $GITHUB_OUTPUT

      - name: read version
        run:  echo "version ${{ steps.versions.outputs.version }}"
